### ISSUE TITLE
camera.chuangmi_039a04_94a7_camera_control can't get the stream video

### ISSUE THREAD

**Issue by Cocosms** [al-one/hass-xiaomi-miot#1866] opened 2024-09-17 23:11 UTC
### Device model / 设备型号

camera.chuangmi_039a04_94a7

### Component version / 插件版本

0.7.20

### HA core version / HA版本

2024.9.2

### Integrated mode / 集成方式

Cloud (云端模式)

### The problem / 问题详情

Keep getting the error:
Error requesting stream: camera.chuangmi_039a04_94a7_camera_control does not support play stream service

Have tried to enable home surveillance, but still can't get the image.

Also, below is my customization.yaml config:
camera.chuangmi_039a04_94a7_camera_control:
  miot_cloud: true
  video_attribute: 2
  keep_streaming: true
  use_motion_stream: true
  sub_motion_stream: true 
  motion_stream_slice: -1

### Entity attributes / 实体属性

```yaml
access_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
model_name: chuangmi.camera.039a04
brand: chuangmi
frontend_stream_type: hls
model: chuangmi.camera.039a04
lan_ip: 192.168.0.103
mac_address: 78:DF:72:25:94:A7
entity_class: MiotCameraEntity
home_room: Белый дом Прихожая
miot_type: urn:miot-spec-v2:device:camera:0000A01C:chuangmi-039a04:1
camera_control.on: true
camera_control.image_rollover: 0
camera_control.night_shot: 2
camera_control.wdr_mode: true
glimmer_full_color-2-6: true
camera_control.recording_mode: 2
camera_control.motion_tracking: false
camera_control.local_storage: true
imi_alarm.alarm_clocks: 
imi_alarm.alarm_clocks_key: 
imi_alarm.baby_wake_switch: false
imi_alarm.baby_sleep_area: 
imi_alarm.babycry_switch: false
stream_status-10-9: 1
stream_status-9-9: 1
motion_detection: true
motion_detection.alarm_interval: 10
detection_sensitivity-5-3: 0
motion_detection_start_time-5-4: 00:00:00
motion_detection_end_time-5-5: 23:59:00
memory_card_management.status: 1
storage_total_space-4-2: 1024
storage_free_space-4-3: 0
storage_used_space-4-4: 1024
indicator_light.on: true
state_updater: cloud
sub_entities: memory_card_management-4.status-1, memory_card_management-4.storage_free_space-3, memory_card_management-4.storage_used_space-4, camera_control-2.on-1, camera_control-2.wdr_mode-5, camera_control-2.glimmer_full_color-6, camera_control-2.motion_tracking-8, indicator_light-3.on-1, motion_detection-5.motion_detection-1, camera_control-2.image_rollover-2, motion_detection-5.alarm_interval-2, camera_control-2.night_shot-3, camera_control-2.recording_mode-7, motion_detection-5.detection_sensitivity-3, indicator_light-3, motion_event
entity_picture: /api/camera_proxy/camera.chuangmi_039a04_94a7_camera_control?token=xxxxxxxxxxxxxxxxxxxxxxxx
friendly_name: Умная камера Camera Control
supported_features: 3
miot_cloud: true
video_attribute: 2
keep_streaming: true
use_motion_stream: true
sub_motion_stream: true
motion_stream_slice: -1
```

### Home Assistant Logs / 系统日志

Регистратор: homeassistant.components.camera
Источник: components/camera/__init__.py:892
интеграция: Камера (документация, проблемы)
Первое сообщение: 17 сентября 2024 г. в 22:48:38 (5 сообщений)
Последнее сообщение: 02:01:07

Error requesting stream: camera.chuangmi_039a04_94a7_camera_control does not support play stream service

**Comment by Cocosms** [comment] 2024-09-18 12:21
btw getting the following errors while trying to use motion_event:
Регистратор: homeassistant.components.stream.stream.camera.chuangmi_039a04_94a7_motion_event
Источник: components/stream/__init__.py:448
интеграция: Stream (документация, проблемы)
Первое сообщение: 15:15:30 (11 сообщений)
Последнее сообщение: 15:19:05

Error from stream worker: Error demuxing stream (INVALIDDATA, Invalid data found when processing input, https://ru.business.smartcamera.api.io.mi.com/common/app/m3u8?data=xxxx%3D%3D&rc4_hash__=xxxx%3D%3D&signature=xxxx%3D&ssecurity=xxxx%3D%3D&_nonce=xxxx&yetAnotherServiceToken=xxxx)
Error from stream worker: Error opening stream (ERRORTYPE_113, Host is unreachable, https://ru.business.smartcamera.api.io.mi.com/common/app/m3u8?data=xxxxx3D%3D&rc4_hash__=xxxxxxxxxxxxxxxew%3D%3D&signature=xxxxxxxxxxx&ssecurity=Qjxxxxxxx%3D&_nonce=xxxxxzf&yetAnotherServiceToken=xxxxxxxx)
Error from stream worker: Error demuxing stream (INVALIDDATA, Invalid data found when processing input, https://ru.business.smartcamera.api.io.mi.com/common/app/m3u8?data=xxxx%3D&rc4_hash__=xxxxQ%3D%3D&signature=Zxxxx2E%3D&ssecurity=xxxx%3D%3D&_nonce=xxxxzh&yetAnotherServiceToken=xxxxI%3D)

**Comment by RE-Kovalev** [comment] 2024-09-22 10:08
Got same problem with C301 camera

**Comment by PlusA2M** [comment] 2024-10-05 20:26
+1 for C700 camera

**Comment by Th30wl** [comment] 2024-10-08 01:26
Same for the C200 Model MJSXJ14CM, chuangmi.camera.046c04
Camera firmware: 5.1.6_0385
Home assistant version: 2024.10.1
Component version: v0.7.20

**Comment by ChanLicher** [comment] 2024-10-08 02:10
The same here for C700, I can only check the one screenshot 10 min before, and I cannot watch the stream either. At least, let me watch the stream

**Comment by Th30wl** [comment] 2024-10-12 18:46
Here's the debug log:

```
Logger: homeassistant.components.camera
Source: components/camera/__init__.py:892
integration: Camera ([documentation](https://www.home-assistant.io/integrations/camera), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+camera%22))
First occurred: 20:41:36 (1 occurrences)
Last logged: 20:41:36

Error requesting stream: camera.chuangmi_046c04_9e28_camera_control does not support play stream service
```

**Comment by eincer** [comment] 2024-10-13 05:53
Same for camera C400:

`Logger: homeassistant.components.camera
Source: components/camera/__init__.py:892
integration: Camera ([documentation](https://www.home-assistant.io/integrations/camera), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+camera%22))
First occurred: 11:51:49 PM (1 occurrences)
Last logged: 11:51:49 PM
Error requesting stream: camera.chuangmi_039a04_08bb_camera_control does not support play stream service`

**Comment by wick3da** [comment] 2024-10-17 06:10
Same for camera C400

+1

**Comment by eincer** [comment] 2024-10-20 05:05
Looks like a duplicate of [1042](https://github.com/al-one/hass-xiaomi-miot/issues/1042) .

But it seems to be affecting multiple models

**Comment by Th30wl** [comment] 2024-10-21 08:06
Is there a way to access the stream directly? Without using the integration. I want to try if it works using Vlc player

**Comment by Th30wl** [comment] 2024-11-04 14:36
I have enabled motion detection on my camera and i can see a preview image of a motion event but when i open it  to see the recording it shows the first frame only and video has 0:00 duration.
Error in the log for this is:
```
Logger: homeassistant.components.stream.stream.camera.chuangmi_046c04_9e28_motion_event
Source: components/stream/__init__.py:448
integration: Stream (documentation, issues)
First occurred: 15:26:57 (6 occurrences)
Last logged: 15:29:39

Error from stream worker: Error demuxing stream (INVALIDDATA, Invalid data found when processing input, https://de.business.smartcamera.api.io.mi.com/common/app/m3u8?data=[I HAVE REMOVED THIS PART])
```

Is the integration broken or I am missing some settings?

**Comment by TahirJalilov** [comment] 2024-11-06 19:00
the same issue, no video on C400

**Comment by cristian-rincon** [comment] 2024-12-05 03:26
Hi, I’m here to report the same issue with chuangmi.camera.021a04 (Mi 360° Home Security Camera 2K Pro) and chuangmi.camera.039a04 (Xiaomi Smart Camera C400)

**Comment by MStankiewiczOfficial** [comment] 2024-12-06 11:12
Still the same problem with chuangmi.camera.029a02

**Comment by Th30wl** [comment] 2024-12-06 13:17
After updating to v1.0.2 I am getting a different error:

```
Logger: miio.miioprotocol
Source: custom_components/xiaomi_miot/core/device.py:919
integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 14:16:29 (1 occurrences)
Last logged: 14:16:29

Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}



Logger: homeassistant.components.camera
Source: components/camera/__init__.py:1085
integration: Camera (documentation, issues)
First occurred: 14:09:31 (1 occurrences)
Last logged: 14:09:31

Timeout getting stream source
```

**Comment by unegade** [comment] 2024-12-11 21:10
I have same problem with C301 camera
I noticed that everyone has problems with cameras that are marked as "miot-local" in miot-spec

**Comment by al-one** [comment] 2024-12-12 02:25
Video streams are not supported.

**Closed by al-one** 2024-12-12 02:25 UTC

**Comment by SpectralDragon** [comment] 2025-02-14 23:30
@al-one Hi, thanks for your hard work, can you please explain, why stream will not supported? That is a soft restriction or you don't have a time for it?
